### ISSUE TITLE
Relative position vectors?

### ISSUE THREAD

**Issue by ameya98** [atomistic-machine-learning/schnetpack-gschnet#5]
In schnetpack's QM9 task, the input has the relative position vectors `r_ij` which are used to compute the relative distances `d_ij`.
However, in this repository I see that only the distances are provided. Is there a way to obtain the position vectors as well?

**Comment by NiklasGebauer** [comment]
Hi @ameya98 ,

I made a small commit (f400b50) to support "input_modules" in the model (just like the NeuralNetworkPotential class in schnetpack). After you pulled and installed the newest version, you can add the following lines to your experiment.yaml:

```yaml
model:
  input_modules:
    - _target_: schnetpack.atomistic.PairwiseDistances
```

Then, the model will compute the relative position vectors Rij and add it to the inputs as the very first step, just as in the schnetpack models.

Best,
Niklas

**Comment by ameya98** [comment]
Thank you so much for your help!
