### ISSUE TITLE
What is the exact version number of pytorch, pytorch_lightning, hydra-core, hydra-colorlog, ase and python?

### ISSUE THREAD

**Issue by Hanxiaoze** [atomistic-machine-learning/schnetpack-gschnet#6]
What is the exact version number of pytorch, pytorch_lightning, hydra-core, hydra-colorlog, ase, python? Can you provide the exact version number for us. I used the setup.py, but got lots of Error because of the version incompatibility. I would really appreciate your help.

**Comment by NiklasGebauer** [comment]
Hi @Hanxiaoze ,

unfortunately, I cannot reproduce version incompatibilities during installation. Did you set up a fresh environment or did you try to install `schnetpack-gschnet` into an existing environment? In a new environment, the packages should install fine. I just set up a new environment and these are the versions that were installed:
```
torch                     2.0.0
pytorch-lightning         2.0.1
hydra-core                1.3.2
hydra-colorlog            1.2.0
ase                       3.22.1
python                    3.11.3
```

However, when running the code to train a model, the `schnetpack` package currently currently causes a problem with `pytorch-lightning>=2.0` as pointed out in https://github.com/atomistic-machine-learning/schnetpack-gschnet/issues/7#issuecomment-1517549027. Please install `pytorch-lightning==1.9` manually until we release a new `schnetpack` version on PyPi (I will take care of this later today).

Hope this helps!
Best,
Niklas
